---
# defaults file for common
observium_base_dir: '{{ observium_dl_dir }}/observium'
observium_dl_dir: '/opt'
observium_dl_package: 'observium-community-latest.tar.gz'
observium_dl_url: 'http://www.observium.org'
observium_debian_pre_reqs:
  - apache2
  - fping
  - graphviz
  - imagemagick
  - ipmitool
  - libapache2-mod-php7.2
  # optional,monitor libvirt virtual machines, install libvirt-bin
  # - libvirt-bin
  - mtr-tiny
  - mysql-server
  - mysql-client
  - php-pear
  - php7.2-cli
  - php7.2-gd
  - php7.2-json
  - php7.2-mysql
  - php7.2-mysqli
  - python-mysqldb
  - rrdtool
  - snmp
  - subversion
  - whois
  - snmp-mibs-downloader
observium_monitor_libvirt_vms: false  #Define if desired to monitor LibVirt VM's
observium_db_info:
  db: 'observium'
  host: '127.0.0.1'
  password: 'observium'
  user: 'observium'
observium_snmp_community_list:   # define a list of default communities to try when adding devices
  - '"observium"'    # requires that the quotes are inside single quotation marks to keep the quotes in the config.php
observium_admin_account_info:
  email: 'observium@{{ pri_domain_name }}'
  email_to: 'root@localhost'
  email_default_only: 'TRUE'
  level: 10
  password: 'observium'
  username: 'admin'
pri_domain_name: 'vagrant.local'
